version: '3.9'
name: 'event_dev'

services:
  redis:
    image: redis:7-alpine
    command: redis-server
    ports:
      - "6379:6379"
    expose:
      - "6379"
    volumes:
      - redis_value:/data

  postgres:
    image: postgres:14
    volumes:
      - postgres_value:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "${POSTGRES_PORT}:5432"

  backend:
    image: standup1990/event:latest
    restart: always
    env_file:
      - ./.env
    volumes:
      - backend_value:/app/data
    ports:
      - "8000:8000"

volumes:
  postgres_value:
  redis_value:
  backend_value:
