name: Event tests

on:
  push:
    branches:
      - develop

jobs:

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    services:

      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: events_db
          POSTGRES_USER: events_user
          POSTGRES_PASSWORD: events_password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt
    - name: Test with pytest
      env:
        POSTGRES_USER: events_user
        POSTGRES_PASSWORD: events_password
        POSTGRES_DB: events_db
        DB_HOST: 127.0.0.1
        DB_PORT: 5432    
      run: |
        pytest event_app


  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Push to repo
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: "StAndUP-ru/funtech"
          event-type: update_remote
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "module": "events", "branch": "develop"}'

  build_and_push_to_docker_hub:
    needs: [dispatch]
    name: Build and Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: ./
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/event:latest
