name: Events backend

on: [push]

jobs:

  linters:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
        linter: ["flake8", "mypy"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt

    - name: Test with ${{ matrix.linter }}
      run: ${{ matrix.linter }} .
          
